---

language: python
python:
  - "3.6"
install:
  - pip install --upgrade pip setuptools pytest
  - pip install coverage nose ordered-set polib pylint requests six
  - pip install pykickstart
script:
  - "for i in *.ks; do ksvalidator -l $i; done"
notifications:
 email: false

...
