---

language: 'python'
python: "2.7"

sudo: 'required'

env:
  - distribution: 'centos'
    version: 'latest'

services:
  - 'docker'

before_install:
  - 'sudo docker pull ${distribution}:${version}'
  - 'container_id=$(mktemp)'
  - 'sudo docker run -id -v="${PWD}":/mnt:ro ${distribution}-${version} > "${container_id}"'
script:
  - 'sudo docker exec "$(cat ${container_id})" for i in $( ls *.ks ); do ksvalidator $i; done'

after_install:
  - 'sudo docker stop "${container_id}"'
  - 'sudo docker rm "$( cat ${ container_id } )"'

...
