---

language: 'python'
python: "2.7"

sudo: 'required'

env:
  - distribution: 'centos'
    version: 'latest'

services:
  - 'docker'

before_install:
  - 'sudo docker pull ${distribution}:${version}'
  - 'sudo docker build --no-cache --rm --file=Dockerfile --tag=${distribution}-${version}'

script:
  - 'container_id=$(mktemp)'
  - 'sudo docker run --detach --privileged --volume="${PWD}":/mnt:ro ${distribution}-${version} > "${container_id}"'
  - 'sudo docker exec "$(cat ${container_id})" for i in $( ls *.ks ); do ksvalidator $i; done'

...
