---

language: 'python'
python: "2.7"

sudo: 'required'

env:
  - distribution: 'centos'
    version: 'latest'

services:
  - 'docker'

before_install:
  - 'sudo docker pull ${distribution}:${version}'
  - 'container_id=$(mktemp)'
  - 'sudo docker run -id --privileged -v="${PWD}":/mnt:ro ${distribution}:${version} > "${container_id}"'
  - 'sudo docker exec "$(cat ${container_id})" yum install -y pykickstart'
script:
  - 'sudo docker exec "$(cat ${container_id})" \
                      for i in $( ls -1 *.ks ); \
                      do 
                        echo "processing $i" && \
                        ksvalidator $i && \
                        [[ $? -ne "0" ]] && echo "pizdeznahoibleat" && exit 1 ; \
                      done'

after_install:
  - 'sudo docker stop "${container_id}"'
  - 'sudo docker rm "$( cat ${ container_id } )"'

...
