---
language: python
python:
  - "2.7"
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y python-pykickstart
script:
  - "ksvalidator -l"
  - "ksvalidator -v"
  - "ksvalidator *.ks"
notifications:
 email: false
...
