---

language: python
python:
  - "3.6"
install:
  - pip install --upgrade pip setuptools pytest
  - pip install coverage nose ordered-set polib pylint requests six
  - pip install pykickstart
script:
  - "ksvalidator -l"
  - "ksvalidator -v"
  - "ksvalidator *.ks"
notifications:
 email: false

...
