---

language: python
python:
  - "3.6"
env:
  - distr: RHEL6
  - distr: RHEL7
  - distr: RHEL8

install:
  - pip install --upgrade pip setuptools pytest
  - pip install coverage nose ordered-set polib pylint requests six
  - pip install pykickstart
script:
  - "for i in *.ks; do ksvalidator --version ${distr} $i; done"
notifications:
 email: false

...
